const BASE_URL = "https://4f2de039-e4b3-45c1-93e2-4873c5ea1a8e-dev.e1-us-east-azure.choreoapis.dev/resource-hub/ballerina";

export const API_ENDPOINTS = {
  LOGIN: `${BASE_URL}/v1.0/login`,
  USER_DETAILS: `${BASE_URL}/user-294/v1.0/details`,
  USER_ADD: `${BASE_URL}/user-294/v1.0/add`,
  USER_DETAILS_BY_ID: (userId) => `${BASE_URL}/user-294/v1.0/details/${userId}`,
  MAINTENANCE_DETAILS: `${BASE_URL}/maintenance-f9f/v1.0/details`,
  MAINTENANCE_DETAILS_BY_ID: (id) => `${BASE_URL}/maintenance-f9f/v1.0/details/${id}`,
  MAINTENANCE_NOTIFICATION: `${BASE_URL}/maintenance-f9f/v1.0/notification`,
  MAINTENANCE_ADD: `${BASE_URL}/maintenance-f9f/v1.0/add`,
  MAINTENANCE_ADD_NOTIFICATION: `${BASE_URL}/maintenance-f9f/v1.0/addnotification`,
  MAINTENANCE_REPORT: `${BASE_URL}/maintenance-f9f/v1.0/report`,
  ASSET_DETAILS: `${BASE_URL}/asset-e99/v1.0/details`,
  ASSET_DETAILS_BY_ID: (id) => `${BASE_URL}/asset-e99/v1.0/details/${id}`,
  ASSET_ADD: `${BASE_URL}/asset-e99/v1.0/add`,
  ASSET_REQUEST_ADD: `${BASE_URL}/assetrequest-9fc/v1.0/add`,
  ASSET_REQUEST_DETAILS: `${BASE_URL}/assetrequest-9fc/v1.0/details`,
  ASSET_REQUEST_DETAILS_BY_USER: (userId) => `${BASE_URL}/assetrequest-9fc/v1.0/details/${userId}`,
  ASSET_REQUEST_DUE_ASSETS: `${BASE_URL}/assetrequest-9fc/v1.0/dueassets`,
  ASSET_REQUEST_DUE_ASSETS_BY_USER: (userId) => `${BASE_URL}/assetrequest-9fc/v1.0/dueassets/${userId}`,
  CALENDAR_MEAL_EVENTS: `${BASE_URL}/calander-7e9/v1.0/mealevents`,
  CALENDAR_MEAL_EVENTS_BY_USER: (userId) => `${BASE_URL}/calander-7e9/v1.0/mealevents/${userId}`,
  CALENDAR_MEAL_EVENTS_ADD: `${BASE_URL}/calander-7e9/v1.0/mealevents/add`,
  CALENDAR_MEAL_EVENTS_DELETE: (eventId) => `${BASE_URL}/calander-7e9/v1.0/mealevents/${eventId}`,
  MEAL_TIME_DETAILS: `${BASE_URL}/mealtime-481/v1.0/details`,
  MEAL_TIME_ADD: `${BASE_URL}/mealtime-481/v1.0/add`,
  MEAL_TIME_DELETE: (mealId) => `${BASE_URL}/mealtime-481/v1.0/details/${mealId}`,
  MEAL_TIME_UPDATE: (mealId) => `${BASE_URL}/mealtime-481/v1.0/details/${mealId}`,
  MEAL_TYPE_DETAILS: `${BASE_URL}/mealtype-899/v1.0/details`,
  MEAL_TYPE_ADD: `${BASE_URL}/mealtype-899/v1.0/add`,
  MEAL_TYPE_DELETE: (mealId) => `${BASE_URL}/mealtype-899/v1.0/details/${mealId}`,
  MEAL_TYPE_UPDATE: (mealId) => `${BASE_URL}/mealtype-899/v1.0/details/${mealId}`,
  SETTINGS_DETAILS: (userId) => `${BASE_URL}/settings-e6f/v1.0/details/${userId}`,
  SETTINGS_UPDATE: (endpoint, userId) => `${BASE_URL}/settings-e6f/v1.0/${endpoint}/${userId}`,
  SETTINGS_PASSWORD_UPDATE: (userId) => `${BASE_URL}/settings-e6f/v1.0/password/${userId}`,
  SETTINGS_PROFILE_UPDATE: (userId) => `${BASE_URL}/settings-e6f/v1.0/profile/${userId}`,
  ADMIN_DASHBOARD_STATS: `${BASE_URL}/dashboard-admin-b74/v1.0/stats`,
  ADMIN_DASHBOARD_RESOURCES: `${BASE_URL}/dashboard-admin-b74/v1.0/resources`,
  ADMIN_DASHBOARD_MEAL_DISTRIBUTION: `${BASE_URL}/dashboard-admin-b74/v1.0/mealdistribution`,
  ADMIN_DASHBOARD_RESOURCE_ALLOCATION: `${BASE_URL}/dashboard-admin-b74/v1.0/resourceallocation`,
  USER_DASHBOARD_STATS: (userId) => `${BASE_URL}/dashboard-user-033/v1.0/stats/${userId}`,
  USER_DASHBOARD_ACTIVITIES: (userId) => `${BASE_URL}/dashboard-user-033/v1.0/activities/${userId}`,
};
